Repository Match-Box-Team/FrontEnd, pull requests merged in 2023-04, with the labels that each got.

#10 feat: Prettier, Lint 설정
  .eslintrc.js
  .prettierrc
  package-lock.json
  package.json
  src/App.tsx
  src/index.tsx
Labels: Bug 🚨, Feature

#14 feat: router 세팅
  .eslintrc.js
  package-lock.json
  package.json
  src/App.tsx
  src/Router.tsx
  src/components/commons/footer/footer.tsx
  src/components/commons/header/header.tsx
  src/components/commons/modals/popup-modal/popup.tsx
  src/components/commons/modals/profile-modal/profile.tsx
  src/components/pages/chat/channel-page/channel.tsx
  src/components/pages/chat/chat-modal/createroom-modal/createroom.tsx
  src/components/pages/chat/chat-modal/roomside-modal/roomside.tsx
  src/components/pages/chat/chat-modal/setroom-modal/setroom.tsx
  src/components/pages/chat/chatroom-page/chatroom.tsx
  src/components/pages/chat/mymsg-page/mymsg.tsx
  src/components/pages/friend/addfriend-page/addfriend.tsx
  src/components/pages/friend/bannedlist-page/bannedlist.tsx
  src/components/pages/friend/friendlist-page/friendlist.tsx
  src/components/pages/game/game-modal/buygame-modal/buygame.tsx
  src/components/pages/game/game-modal/matching-modal/matching.tsx
  src/components/pages/game/game-modal/readygame-modal/readygame.tsx
  src/components/pages/game/gamerecord-page/gamerecord.tsx
  src/components/pages/game/gameshop-page/gameshop.tsx
  src/components/pages/game/playgame-page/playgame.tsx
  src/components/pages/game/watchgame-page/watchgame.tsx
  src/components/pages/login/auth-page/auth.tsx
  src/components/pages/login/login-page/login.tsx
  src/components/pages/profiles/chatadmin-modal/chatadmin.tsx
  src/components/pages/profiles/chatnormal-modal/chatnormal.tsx
  src/components/pages/profiles/editmy-modal/editmy.tsx
  src/components/pages/profiles/friend-modal/friend.tsx
  src/components/pages/profiles/friend-page/FriendProfile.tsx
  src/components/pages/profiles/friend-page/friend.tsx
  src/components/pages/profiles/my-page/MyProfile.tsx
  src/components/pages/profiles/my-page/my.tsx
  src/components/pages/profiles/profile-modal/chatadmin-modal/chatadmin.tsx
  src/components/pages/profiles/profile-modal/chatnormal-modal/chatnormal.tsx
  src/components/pages/profiles/profile-modal/editmy-modal/editmy.tsx
  src/components/pages/profiles/profile-modal/friend-modal/friend.tsx
Labels: Feature

#16 Feature/15 레이아웃 개발
  package-lock.json
  package.json
  src/components/commons/footer/Footer.tsx
  src/components/commons/header/Header.tsx
  src/components/commons/layout/Layout.tsx
  src/components/commons/layout/MainGrind.tsx
  src/components/pages/chat/channel-page/Channel.tsx
  src/components/pages/chat/chatroom-page/ChatRoom.tsx
  src/components/pages/login/auth-page/Auth.tsx
Labels: Feature

#18 Feature/11 global style(전역스타일), theme 작성, Normalize(모든 브라우저에 대한 css 설정), 폰트 추가
  .eslintrc.js
  package-lock.json
  package.json
  src/App.tsx
  src/assets/font/NanumGothic.woff
  src/assets/font/NanumGothic.woff2
  src/assets/font/SEBANG Gothic.woff
  src/assets/font/SEBANG Gothic.woff2
  src/assets/font/font.css
  src/styles/GlobalStyle.ts
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: Feature

#19 Feature/7 feature 헤더 푸터
  .eslintrc.js
  package-lock.json
  package.json
  src/assets/icon/back.svg
  src/assets/icon/chat-icon-clicked.svg
  src/assets/icon/chat-icon.svg
  src/assets/icon/friend-icon-clicked.svg
  src/assets/icon/friend-icon.svg
  src/assets/icon/game-icon-clicked.svg
  src/assets/icon/game-icon.svg
  src/assets/icon/hamburger.svg
  src/assets/icon/my-icon-clicked.svg
  src/assets/icon/my-icon.svg
  src/components/commons/footer/Footer.tsx
  src/components/commons/header/Header.tsx
  src/components/commons/header/Toggle.tsx
  src/components/pages/chat/channel-page/Channel.tsx
  src/components/pages/chat/chatroom-page/ChatRoom.tsx
  src/components/pages/chat/mymsg-page/MyMsg.tsx
  src/components/pages/friend/bannedlist-page/BannedList.tsx
  src/components/pages/friend/friendlist-page/FriendList.tsx
  src/components/pages/game/gameshop-page/GameShop.tsx
  src/components/pages/profiles/my-page/MyProfile.tsx
  svg.d.ts
  tsconfig.json
Labels: Feature

#20 Feature/13 feature 채팅방 생성 모달
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/Router.tsx
  src/components/pages/chat/channel-page/Channel.tsx
  src/components/pages/chat/chat-modal/createroom-modal/Createroom.tsx
  src/components/pages/chat/chat-modal/createroom-modal/PublicToggleButton.tsx
  src/recoil/locals/chat/atoms/atom.tsx
Labels: Feature

#23 Feature/12 공개 채널 페이지
  .eslintrc.js
  .gitignore
  package-lock.json
  package.json
  src/assets/icon/create-room-icon.svg
  src/components/commons/error/ErrorPopup.tsx
  src/components/pages/chat/channel-page/Channel.tsx
  src/components/pages/chat/channel-page/sub-components/ChannelList.tsx
  src/components/pages/chat/channel-page/sub-components/CreateChannel.tsx
  src/components/pages/chat/chat-modal/createroom-modal/Createroom.tsx
  src/index.tsx
  src/recoil/globals/atoms/atom.tsx
  src/recoil/locals/chat/atoms/atom.tsx
  src/recoil/locals/chat/selectors/selector.tsx
Labels: Feature

#21 refact: createRoom에 각종 실수 수정, 주석 추가
  src/components/pages/chat/channel-page/Channel.tsx
  src/components/pages/chat/chat-modal/createroom-modal/Createroom.tsx
Labels: Feature

#26 Feature/13 feature 채팅방 모달들 구현
  package-lock.json
  package.json
  src/components/commons/modals/popup-modal/Popup.tsx
  src/components/pages/chat/channel-page/Channel.tsx
  src/components/pages/chat/channel-page/sub-components/CreateChannel.tsx
  src/components/pages/chat/chat-modal/createroom-modal/Createroom.tsx
  src/components/pages/chat/chat-modal/invite-modal/Invite.tsx
  src/components/pages/chat/chat-modal/setroom-modal/SetRoom.tsx
  src/components/pages/chat/chatroom-page/ChatRoom.tsx
Labels: Feature

#27 Feature/25 내가 속한 페이지
  src/api/ChatRoomInfo.ts
  src/api/ProfileImge.ts
  src/components/pages/chat/mymsg-page/MyMsg.tsx
  src/components/pages/chat/mymsg-page/sub-components/MyMsgList.tsx
Labels: Feature

#28 feat: 프로필 모달 구현
  .eslintrc.js
  src/assets/icon/ban.svg
  src/assets/icon/dm.svg
  src/assets/icon/game.svg
  src/assets/icon/kick.svg
  src/assets/icon/mute.svg
  src/assets/icon/not-ban.svg
  src/assets/icon/profile-modal-exit.svg
  src/assets/icon/unmute.svg
  src/components/commons/footer/Footer.tsx
  src/components/commons/modals/profile-modal/Profile.tsx
  src/components/commons/modals/profile-modal/ProfileFooter.tsx
  src/components/pages/chat/chatroom-page/ChatRoom.tsx
Labels: Feature

#31 Bug/30 공개 채널 페이지
  src/components/commons/layout/MainGrind.tsx
  src/components/pages/chat/channel-page/sub-components/ChannelList.tsx
  src/components/pages/chat/channel-page/sub-components/PwdSetModal.tsx
  src/components/pages/chat/mymsg-page/sub-components/MyMsgList.tsx
Labels: Bug 🚨

#32 feat:게임레디 틀
  src/components/pages/game/game-modal/readygame-modal/ReadyGame.tsx
  src/components/pages/profiles/friend-page/FriendProfile.tsx
Labels: Feature

#38 refactor: 리코일에서 토큰을 가져오는 코드로 전환
  package-lock.json
  package.json
  src/api/ChatRoomInfo.ts
  src/api/ProfileImge.ts
  src/components/commons/modals/profile-modal/ProfileFooter.tsx
  src/components/pages/chat/channel-page/sub-components/ChannelList.tsx
  src/components/pages/chat/chat-modal/createroom-modal/Createroom.tsx
  src/components/pages/chat/chat-modal/invite-modal/Invite.tsx
  src/components/pages/chat/chat-modal/setroom-modal/SetRoom.tsx
  src/components/pages/chat/mymsg-page/sub-components/MyMsgList.tsx
  src/components/pages/login/auth-page/Auth.tsx
  src/components/pages/login/login-page/CheckLogin.tsx
  src/components/pages/profiles/my-page/MyProfile.tsx
  src/components/pages/profiles/profile-modal/editmy-modal/EditMy.tsx
Labels: Refactor 🌈

#39 refactor: 유저 정보에 recoil persist 적용
  package-lock.json
  package.json
  src/components/pages/login/auth-page/Auth.tsx
  src/recoil/locals/login/atoms/atom.tsx
Labels: Refactor 🌈

#40 Featue/6 채팅방페이지 : 로직 구현
  package-lock.json
  package.json
  src/Router.tsx
  src/api/Channel.ts
  src/api/Example.tsx
  src/api/Friends.ts
  src/api/index.ts
  src/components/pages/chat/chat-modal/chatroom-modal/ChatRoom.tsx
  src/components/pages/chat/chatroom-page/ChatRoomt.tsx
  src/components/pages/chat/chatroom-page/components/InputChat.tsx
  src/components/pages/chat/chatroom-page/components/Message.tsx
  src/components/pages/chat/chatroom-page/components/MessageList.tsx
  src/components/pages/chat/chatroom-page/index.tsx
  src/index.tsx
  src/recoil/locals/chat/atoms/messagesAtom.ts
Labels: Feature

#42 fix: 채팅룸과 리액트 쿼리에서 리코일을 통해서 토큰을 받아오는 방식으로 변경
  package-lock.json
  package.json
  src/api/Account.ts
  src/api/Channel.ts
  src/api/Example.tsx
  src/api/Friends.ts
  src/api/Game.ts
  src/api/index.ts
  src/components/pages/chat/chatroom-page/ChatRoomt.tsx
Labels: Refactor 🌈

#43 Feature/33 게임 레디 모달
  src/components/pages/game/game-modal/readygame-modal/ReadyGame.tsx
  src/components/pages/game/playgame-page/PlayGame.tsx
  src/components/pages/game/playgame-page/games/PingPong.tsx
Labels: Feature

#51 Featue/6 채팅방페이지: 하단 채팅 입력창 css 수정 / 프로젝트 전체: 최상위 폴더에 rem 설정
  src/components/commons/layout/MainGrind.tsx
  src/components/pages/chat/chatroom-page/components/InputChat.tsx
  src/components/pages/chat/chatroom-page/components/MessageList.tsx
  src/index.tsx
Labels: Feature

#48 Feature/8 feature 로그인인증프로필 구현
  package-lock.json
  package.json
  src/components/pages/chat/chatroom-page/index.tsx
  src/components/pages/login/auth-page/Auth.tsx
  src/components/pages/login/login-page/CheckLogin.tsx
  src/components/pages/login/login-page/Login.tsx
  src/recoil/locals/login/atoms/atom.tsx
Labels: Refactor 🌈

#55 feat: 친구 차단 목록
  src/assets/icon/ban-restore.svg
  src/components/pages/friend/bannedlist-page/BannedList.tsx
Labels: Feature

#58 Feature/46 feature 채팅방 사이드 모달 구현
  src/App.tsx
  src/api/AddFriend.ts
  src/api/ChatRoomInfo.ts
  src/api/InviteChatRoom.ts
  src/api/SetAdmin.ts
  src/assets/icon/plus.svg
  src/assets/icon/what.svg
  src/components/commons/header/Header.tsx
  src/components/commons/modals/popup-modal/Popup.tsx
  src/components/commons/modals/profile-modal/Profile.tsx
  src/components/commons/modals/profile-modal/ProfileFooter.tsx
  src/components/pages/chat/chat-modal/invite-modal/Invite.tsx
  src/components/pages/chat/chat-modal/roomside-modal/RoomSide.tsx
  src/components/pages/chat/chat-modal/setroom-modal/SetRoom.tsx
  src/components/pages/chat/chatroom-page/ChatRoomt.tsx
  src/components/pages/chat/chatroom-page/components/Message.tsx
  src/components/pages/chat/chatroom-page/index.tsx
Labels: Feature

#61 Refactor/49 refactor css 리팩토링
  src/api/BuyGame.ts
  src/api/GetGames.ts
  src/components/pages/game/game-modal/buygame-modal/BuyGame.tsx
  src/components/pages/game/gameshop-page/GameShop.tsx
  src/components/pages/profiles/my-page/MyProfile.tsx
  src/components/pages/profiles/profile-modal/editmy-modal/EditMy.tsx
Labels: Refactor 🌈

#62 Feature/22 게임 소켓 플레이
  src/Router.tsx
  src/components/pages/game/game-modal/readygame-modal/ReadyGame.tsx
  src/components/pages/game/playgame-page/PlayGame.tsx
  src/components/pages/game/playgame-page/game-socket/GameSocketContext.tsx
  src/components/pages/game/playgame-page/game-socket/GameSocketProvider.tsx
  src/components/pages/game/playgame-page/games/PingPong.tsx
  src/components/pages/profiles/friend-page/FriendProfile.tsx
  src/components/pages/profiles/my-page/MyProfile.tsx
Labels: Feature

#64 bug: 핑퐁 게임 렌더링 픽스
  src/components/pages/game/playgame-page/games/PingPong.tsx
Labels: Bug 🚨
