Repository Match-Box-Team/FrontEnd, pull requests merged in 2023-05, with the labels that each got.

#68 refactor: 친구 상태 추가
  src/components/pages/friend/bannedlist-page/BannedList.tsx
Labels: Refactor 🌈

#67 Feature/65 feature 게임 초대 수락 모달과 게임 초대 기능 구현
  src/components/commons/modals/popup-modal/Popup.tsx
  src/components/pages/game/game-modal/accept-game-modal/AcceptModal.tsx
  src/components/pages/game/game-modal/accept-waiting-modal/AcceptWaiting.tsx
  src/components/pages/game/game-modal/buygame-modal/BuyGame.tsx
  src/components/pages/login/login-page/CheckLogin.tsx
  src/components/pages/login/login-page/Login.tsx
  src/components/pages/profiles/my-page/MyProfile.tsx
Labels: Feature

#73 feat: 게임 준비방 구현중...
  src/components/pages/game/game-modal/accept-game-modal/AcceptModal.tsx
  src/components/pages/game/game-modal/accept-waiting-modal/AcceptWaiting.tsx
  src/components/pages/login/login-page/CheckLogin.tsx
Labels: Feature

#72 Feature/59 feature 친구 페이지 친구 추가
  src/Router.tsx
  src/components/pages/friend/addfriend-modal/AddFriend.tsx
  src/components/pages/friend/addfriend-page/AddFriend.tsx
  src/components/pages/friend/bannedlist-page/BannedList.tsx
  src/components/pages/friend/friendlist-page/FriendList.tsx
  src/components/pages/friend/friendlist-page/components/AddFriends.tsx
Labels: Feature

#74 Feature/54 친구목록 페이지 만들기: 모달 및 모달에서 친구 추가, 밴을 할 시 친구목록 업데이트
  src/api/Friends.ts
  src/components/commons/modals/profile-modal/Profile.tsx
  src/components/commons/modals/profile-modal/ProfileFooter.tsx
  src/components/pages/friend/addfriend-modal/AddFriend.tsx
  src/components/pages/friend/friendlist-page/components/FriendDetailList.tsx
  src/components/pages/friend/friendlist-page/components/FrinedDetail.tsx
  src/components/pages/friend/friendlist-page/components/MyProfile.tsx
  src/components/pages/friend/friendlist-page/index.tsx
Labels: Feature

#76 feat: 친구 상세 프로필
  src/components/commons/modals/profile-modal/ProfileFooter.tsx
  src/components/pages/friend/addfriend-modal/AddFriend.tsx
  src/components/pages/friend/friendlist-page/components/AddFriends.tsx
  src/components/pages/profiles/friend-page/FriendProfile.tsx
Labels: Feature

#78 feat: 친구 프로필 dm 채팅
  src/components/commons/modals/profile-modal/ProfileFooter.tsx
  src/components/pages/chat/chat-modal/roomside-modal/RoomSide.tsx
  src/components/pages/chat/chatroom-page/ChatRoomt.tsx
  src/components/pages/chat/chatroom-page/index.tsx
Labels: Feature

#79 Feature/69 feature 게임 준비 방 생성
  src/Router.tsx
  src/api/GameWatch.ts
  src/components/pages/game/game-modal/accept-game-modal/AcceptModal.tsx
  src/components/pages/game/game-modal/accept-waiting-modal/AcceptWaiting.tsx
  src/components/pages/game/game-modal/readygame-modal/Checkbox.tsx
  src/components/pages/game/game-modal/readygame-modal/ReadyGame.tsx
  src/components/pages/game/ready-game-page/ReadyGamePage.tsx
  src/components/pages/login/login-page/CheckLogin.tsx
  src/components/pages/login/login-page/LoginSocketContext.tsx
  src/components/pages/profiles/friend-page/FriendProfile.tsx
  src/components/pages/profiles/my-page/MyProfile.tsx
Labels: Feature

#80 Featrue/77 게임 승패 기록
  src/components/pages/game/playgame-page/PlayGame.tsx
Labels: Feature

#85 Refactor/84 refactor 마이 페이지 게임 선택 상태 관리 코드 수정
  src/Router.tsx
  src/components/pages/chat/chat-modal/createroom-modal/Createroom.tsx
  src/components/pages/game/game-modal/matching-modal/Matching.tsx
  src/components/pages/game/gameshop-page/GameShop.tsx
  src/components/pages/profiles/my-page/MyProfile.tsx
Labels: Refactor 🌈

#89 Feature/82 매칭유저 게임 연결
  src/components/pages/game/game-modal/readygame-modal/ReadyGame.tsx
  src/components/pages/game/playgame-page/games/PingPong.tsx
Labels: Feature

#90 Feature/88 refactor 채팅방을 나간 유저의 채팅 내역 관리
  src/api/Channel.ts
  src/api/ProfileImge.ts
  src/components/commons/modals/profile-modal/Profile.tsx
  src/components/commons/modals/profile-modal/ProfileFooter.tsx
  src/components/pages/chat/chatroom-page/ChatRoomt.tsx
Labels: Refactor 🌈

#92 Bug/91 bug 채팅방 내에서 프로필 눌렀을 때만 isadmin api 요청 사용
  src/components/commons/modals/profile-modal/Profile.tsx
  src/components/commons/modals/profile-modal/ProfileFooter.tsx
  src/components/pages/chat/chatroom-page/ChatRoomt.tsx
  src/components/pages/chat/mymsg-page/sub-components/MyMsgList.tsx
  src/components/pages/login/login-page/CheckLogin.tsx
  src/components/pages/login/login-page/Login.tsx
Labels: Bug 🚨

#96 feat: 룸별로 게임
  src/Router.tsx
  src/components/pages/game/game-modal/readygame-modal/ReadyGame.tsx
Labels: Feature

#95 refactor: 채팅방에서 리코일 대신 url 경로의 채널 아이디 사용
  src/components/commons/modals/profile-modal/Profile.tsx
  src/components/commons/modals/profile-modal/ProfileFooter.tsx
  src/components/pages/chat/chat-modal/invite-modal/Invite.tsx
  src/components/pages/chat/chat-modal/roomside-modal/RoomSide.tsx
  src/components/pages/chat/chat-modal/setroom-modal/SetRoom.tsx
  src/components/pages/chat/chatroom-page/ChatRoomt.tsx
Labels: Refactor 🌈

#101 ProfileFooter의 mute 아이콘이 바로바로 적용되지 않는 문제
  src/api/Channel.ts
  src/components/commons/modals/profile-modal/ProfileFooter.tsx
  src/components/pages/chat/chatroom-page/ChatRoomt.tsx
  src/components/pages/chat/chatroom-page/index.tsx
Labels: Bug 🚨

#103 Bug/102 bug 다중 게임 실시간 렌더링 안됨 버그
  src/components/pages/game/game-modal/readygame-modal/ReadyGame.tsx
  src/components/pages/game/playgame-page/PlayGame.tsx
  src/components/pages/game/playgame-page/games/PingPong.tsx
Labels: Bug 🚨

#106 Refactor/104 refactor 코드 인증 유저 정보 쿠키 대신 state로 관리
  src/api/Channel.ts
  src/components/commons/error/ErrorPopupNav.tsx
  src/components/pages/login/auth-page/Auth.tsx
  src/components/pages/login/login-page/Login.tsx
Labels: Refactor 🌈

#111 Feature/108 feature 매칭 취소 게임 중 나감 등등 처리
  src/components/commons/error/ErrorPopup.tsx
  src/components/pages/chat/channel-page/sub-components/ChannelList.tsx
  src/components/pages/game/game-modal/matching-modal/Matching.tsx
  src/components/pages/game/playgame-page/PlayGame.tsx
  src/components/pages/profiles/my-page/MyProfile.tsx
Labels: Feature

#113 fix/108 fix Merge 실수 수정
  src/components/commons/error/ErrorPopup.tsx
Labels: Feature

#116 refactor: friends 기능 에러 모달 사용
  src/components/commons/error/ErrorPopupNav.tsx
  src/components/commons/modals/profile-modal/ProfileFooter.tsx
  src/components/pages/friend/addfriend-modal/AddFriend.tsx
  src/components/pages/friend/bannedlist-page/BannedList.tsx
  src/components/pages/login/auth-page/Auth.tsx
  src/components/pages/login/login-page/Login.tsx
Labels: Refactor 🌈

#118 Refactor/117 refactor channels 기능 에러 모달 사용
  src/components/pages/chat/chat-modal/createroom-modal/Createroom.tsx
  src/components/pages/chat/chat-modal/invite-modal/Invite.tsx
  src/components/pages/chat/chat-modal/roomside-modal/RoomSide.tsx
  src/components/pages/chat/chat-modal/setroom-modal/SetRoom.tsx
  src/components/pages/chat/chatroom-page/ChatRoomt.tsx
Labels: Refactor 🌈

#120 bug: 내가 속한 채널이 없을 경우 에러 모달 출력되는 문제 해결
  src/components/commons/error/ErrorPopupNav.tsx
  src/components/pages/chat/mymsg-page/sub-components/MyMsgList.tsx
Labels: Bug 🚨

#125 bug: 킥 소켓 사용
  src/api/Channel.ts
  src/components/commons/error/ErrorPopupNav.tsx
  src/components/commons/modals/profile-modal/Profile.tsx
  src/components/commons/modals/profile-modal/ProfileFooter.tsx
  src/components/pages/chat/chatroom-page/ChatRoomt.tsx
  src/components/pages/chat/chatroom-page/index.tsx
Labels: Bug 🚨, Refactor 🌈

#129 Refactor/128 refactor 백엔드 url(localhost, 127.0.0.1) env 변수 사용하도록 수정
  src/api/AddFriend.ts
  src/api/BuyGame.ts
  src/api/ChatRoomInfo.ts
  src/api/GameWatch.ts
  src/api/GetGames.ts
  src/api/InviteChatRoom.ts
  src/api/ProfileImge.ts
  src/api/SetAdmin.ts
  src/components/pages/chat/channel-page/sub-components/ChannelList.tsx
  src/components/pages/chat/chat-modal/createroom-modal/Createroom.tsx
  src/components/pages/chat/chat-modal/invite-modal/Invite.tsx
  src/components/pages/chat/chat-modal/roomside-modal/RoomSide.tsx
  src/components/pages/chat/chat-modal/setroom-modal/SetRoom.tsx
  src/components/pages/chat/mymsg-page/sub-components/MyMsgList.tsx
  src/components/pages/login/login-page/CheckLogin.tsx
  src/components/pages/login/login-page/Login.tsx
  src/components/pages/profiles/my-page/MyProfile.tsx
  src/components/pages/profiles/profile-modal/editmy-modal/EditMy.tsx
Labels: Refactor 🌈

#133 fix: 관리자 아닌 유저가 관리자 설정을 시도한 경우
  src/components/pages/chat/chat-modal/roomside-modal/RoomSide.tsx
Labels: Bug 🚨

#134 bug: 채널 리스트 페이지 새로고침 이슈 해결
  src/components/pages/chat/channel-page/sub-components/ChannelList.tsx
  src/components/pages/chat/mymsg-page/sub-components/MyMsgList.tsx
Labels: Bug 🚨

#137 refactor: 이메일 양식 수정 및 console.log 제거
  src/components/pages/game/game-modal/accept-game-modal/AcceptModal.tsx
  src/components/pages/game/game-modal/accept-waiting-modal/AcceptWaiting.tsx
  src/components/pages/game/game-modal/matching-modal/Matching.tsx
  src/components/pages/game/game-modal/readygame-modal/ReadyGame.tsx
  src/components/pages/game/playgame-page/games/PingPong.tsx
  src/components/pages/game/watchgame-page/GamePage.tsx
  src/components/pages/login/login-page/CheckLogin.tsx
  src/components/pages/login/login-page/Login.tsx
  src/components/pages/profiles/friend-page/FriendProfile.tsx
Labels: Refactor 🌈

#139 refactor: 채팅 소켓 에러 메시지 분리
  src/components/pages/chat/chatroom-page/ChatRoomt.tsx
  src/components/pages/chat/chatroom-page/index.tsx
Labels: Refactor 🌈

#141 Bug/140 bug 게임 준비 취소
  src/components/pages/friend/friendlist-page/components/MyProfile.tsx
  src/components/pages/game/game-modal/readygame-modal/ReadyGame.tsx
  src/components/pages/game/ready-game-page/ReadyGamePage.tsx
Labels: Bug 🚨

#142 fix: gameStartError socker.off 추가
  src/components/pages/game/game-modal/readygame-modal/ReadyGame.tsx
Labels: Bug 🚨

#146 Refactor/145 refactor 게임 페이지 consoleerror error 모달 수정
  src/components/pages/game/watchgame-page/GamePage.tsx
Labels: Refactor 🌈

#154 Feature/153: 지워진 git issue, pull request template 재 업로드
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/refactoring.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Docs 📝

#158 Refactor/157 refactor gamewatchid 없는 방 들어갔을 때 처리 및 playgame쪽 any 수정
  src/components/pages/game/game-modal/readygame-modal/ReadyGame.tsx
  src/components/pages/game/playgame-page/PlayGame.tsx
  src/components/pages/game/ready-game-page/ReadyGamePage.tsx
Labels: Refactor 🌈

#160 Refactor/156 pinpong any 타입 제거
  src/components/pages/game/playgame-page/games/PingPong.tsx
Labels: Refactor 🌈

#162 Bug/161 bug 내가 속한 채널 목록 페이지 불필요한 랜더링 이슈
  src/api/Channel.ts
  src/components/commons/header/Header.tsx
  src/components/pages/chat/chatroom-page/ChatRoomt.tsx
  src/components/pages/chat/mymsg-page/sub-components/MyMsgList.tsx
Labels: Bug 🚨

#163 Develop merge to main(Final!!)
  src/api/Channel.ts
  src/components/commons/header/Header.tsx
  src/components/pages/chat/chatroom-page/ChatRoomt.tsx
  src/components/pages/chat/mymsg-page/sub-components/MyMsgList.tsx
  src/components/pages/game/game-modal/readygame-modal/ReadyGame.tsx
  src/components/pages/game/playgame-page/PlayGame.tsx
  src/components/pages/game/playgame-page/games/PingPong.tsx
  src/components/pages/game/ready-game-page/ReadyGamePage.tsx
Labels: Feature
